name: Build for Linux and Android

on:
  push:
      tags: ["v[12].[0-9]+.[0-9]+"]

jobs:
  build:
      name: Build Linux
      runs-on: ubuntu-latest
      steps:
        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: '6.6.1'
            host: 'linux'
            target: 'desktop'
            arch: 'gcc_64'
            modules: 'qtconnectivity'
            tools: 'tools_cmake tools_ninja'
        - name: Run qt-cmake
          run: "mkdir build && $QT_ROOT_DIR/bin/qt-cmake -G Ninja -S $GITHUB_WORKSPACE -B build"
        - name: Build
          run: "cd build && $QT_ROOT_DIR/Tools/Ninja/ninja"
