name: Build for Linux and Android

on:
  push:
      branches: ["android-workflow-test"]
      tags: ["v[12].[0-9]+.[0-9]+"]

jobs:
  build-linux:
      name: Build Linux AppImage
      runs-on: ubuntu-20.04

      steps:
        - uses: actions/checkout@v4

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: '6.6.1'
            host: 'linux'
            target: 'desktop'
            arch: 'gcc_64'
            modules: 'qtconnectivity'
            tools: 'tools_cmake tools_ninja'

        - name: Install Qt deps
          run: sudo apt-get install -y libxcb-cursor0

        - name: Install linuxdeplotqt
          uses: AnimMouse/setup-appimage@v1
          with:
            name: linuxdeployqt
            url: https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage

        - name: Run qt-cmake
          run: 'mkdir build && $Qt6_DIR/bin/qt-cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_MAKE_PROGRAM="$IQTA_TOOLS/Ninja/ninja" -G Ninja -S ${{github.workspace}} -B build'

        - name: Build
          run: "cd build && $IQTA_TOOLS/Ninja/ninja"

        - name: Create AppDir
          run: |
            mkdir AppDir
            cd AppDir
            mkdir usr
            cd usr
            mkdir bin lib share
            mv ../../build/appBTCar bin/BTCar
            cd share
            mkdir applications icons
            mkdir icons/hicolor
            mkdir icons/hicolor/256x256
            mkdir icons/hicolor/256x256/apps
            mv ../../../images/logo.png icons/hicolor/256x256/apps/BTCar.png
            printf "[Desktop Entry]\nType=Application\nName=BTCar\nComment=Simple but powerful SPP client\nExec=BTCar\nIcon=BTCar\nCategories=Education;\n" >> applications/BTCar.desktop

        - name: Run linuxdeployqt
          run: linuxdeployqt AppDir/usr/share/applications/BTCar.desktop -qmake=$Qt6_DIR/bin/qmake -appimage

  build-android:
      name: Build Android APK
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: '6.6.1'
            host: 'linux'
            target: 'android'
            arch: 'android_arm64_v8a'
            modules: 'qtconnectivity'
            tools: 'tools_cmake tools_ninja'
