name: Build for Linux and Android

on:
  push:
    branches: ["android-workflow-test"]
    tags: ["v[12].[0-9]+.[0-9]+"]

jobs:
  build-linux-deb:
    name: Build Linux deb and rpm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.1'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          modules: 'qtconnectivity'
          tools: 'tools_cmake tools_ninja'

      - name: Install rpm
        run: sudo apt-get install -y rpm

      - name: Build
        run: |
          mkdir build
          $Qt6_DIR/bin/qt-cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX="/tmp/induwara/BTCar" -DCMAKE_MAKE_PROGRAM="$IQTA_TOOLS/Ninja/ninja" -G Ninja -S ${{github.workspace}} -B build
          cd build
          $IQTA_TOOLS/CMake/bin/cmake --build .

      - name: Package deb and rpm
        run: |
          cd build
          $IQTA_TOOLS/CMake/bin/cmake --install .
          $IQTA_TOOLS/CMake/bin/cpack -G "DEB;RPM"

      - name: Upload deb and rpm
        uses: actions/upload-artifact@v4
        with:
          name: btcar-linux
          path: |
            build/BTCar-0.1-Linux.deb
            build/BTCar-0.1-Linux.rpm

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.1'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          modules: 'qtconnectivity'
          tools: 'tools_cmake tools_ninja'

      - name: Install Qt for Android
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.1'
          host: 'linux'
          target: 'android'
          arch: 'android_arm64_v8a'
          modules: 'qtconnectivity'

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Android SDK
        run: '/usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "ndk;25.1.8937393" "platforms;android-33" "platform-tools" "build-tools;33.0.0"'

      - name: Build
        run: |
          mkdir build
          $Qt6_DIR/bin/qt-cmake -DQt6LinguistTools_DIR="$Qt6_DIR/../gcc_64/lib/cmake/Qt6LinguistTools" -DQT_HOST_PATH="$Qt6_DIR/../gcc_64" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_MAKE_PROGRAM="$IQTA_TOOLS/Ninja/ninja" -G Ninja -S ${{github.workspace}} -B build
          cd build
          $IQTA_TOOLS/CMake/bin/cmake --build .

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: btcar-android
          path: /home/runner/work/BTCar/BTCar/build/android-appBTCar-deployment-settings.json
