name: Build for Linux

on:
  push:
      branches: ["master"]
      tags: ["v[12].[0-9]+.[0-9]+"]

jobs:
  build:
      name: Build Linux
      runs-on: ubuntu-latest
      steps:
        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: '6.6.1'
            host: 'linux'
            target: 'desktop'
            arch: 'gcc_64'
            modules: 'qtconnectivity'
            tools: 'tools_cmake tools_ninja'
