name: Build for Linux and Android

on:
  push:
      branches: ["master"]
      tags: ["v[12].[0-9]+.[0-9]+"]

jobs:
  build:
      name: Build Linux
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: '6.6.1'
            host: 'linux'
            target: 'desktop'
            arch: 'gcc_64'
            modules: 'qtconnectivity'
            tools: 'tools_cmake tools_ninja'
        - name: Run qt-cmake
          run: 'mkdir build && $Qt6_DIR/bin/qt-cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_MAKE_PROGRAM="$IQTA_TOOLS/Ninja/ninja" -G Ninja -S ${{github.workspace}} -B build'
        - name: Build
          run: "cd build && $IQTA_TOOLS/Ninja/ninja"
        - name: Upload executable
          uses: actions/upload-artifact@v4
          with:
            name: BTCar
            path: build/appBTCar
