name: Build for Linux and Android

on:
  push:
    branches: ["android-workflow-test"]
    tags: ["v[12].[0-9]+.[0-9]+"]

jobs:
  build-linux:
    name: Build Linux AppImage
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.1'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          modules: 'qtconnectivity'
          tools: 'tools_cmake tools_ninja'

      - name: Install Qt deps
        run: sudo apt-get install -y libxcb-cursor0

      - name: Install linuxdeplotqt
        uses: AnimMouse/setup-appimage@v1
        with:
          name: linuxdeployqt
          url: https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage

      - name: Build
        run: |
          mkdir build
          $Qt6_DIR/bin/qt-cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX="/tmp/BTCar" -DCMAKE_MAKE_PROGRAM="$IQTA_TOOLS/Ninja/ninja" -G Ninja -S ${{github.workspace}} -B build
          cd build
          $IQTA_TOOLS/CMake/bin/cmake --build .
          $IQTA_TOOLS/CMake/bin/cmake --install .
          cpack -G DEB

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BTCar.deb
          path: BTCar-0.1-Linux.deb

  build-android:
    if: ${{false}}
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.1'
          host: 'linux'
          target: 'android'
          arch: 'android_arm64_v8a'
          modules: 'qtconnectivity'

      - name: Install CMake and Ninja
        run: "sudo apt-get install -y ninja-build cmake"

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Android SDK
        run: '/usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "ndk;25.1.8937393" "platforms;android-33" "platform-tools" "build-tools;33.0.0"'

      - name: Build
        run: 'mkdir build && $Qt6_DIR/bin/qt-cmake -DCMAKE_BUILD_TYPE="Release" -G Ninja -S ${{github.workspace}} -B build && cd build && ninja'
